### ISSUE TITLE
KeyError: "['true'] not in index"

### ISSUE THREAD

**Issue by ranmao** [TonyEinstein/informer_ChineseNotes#1]
>>>>>>>predicting :  3_informer_C5_MS  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
本次实验预测未来的时间范围： ['2022-02-11 00:00:00', '2022-02-11 00:15:00', '2022-02-11 00:30:00', '2022-02-11 00:45:00', '2022-02-11 01:00:00', '2022-02-11 01:15:00', '2022-02-11 01:30:00', '2022-02-11 01:45:00', '2022-02-11 02:00:00', '2022-02-11 02:15:00', '2022-02-11 02:30:00', '2022-02-11 02:45:00', '2022-02-11 03:00:00', '2022-02-11 03:15:00', '2022-02-11 03:30:00', '2022-02-11 03:45:00', '2022-02-11 04:00:00', '2022-02-11 04:15:00', '2022-02-11 04:30:00', '2022-02-11 04:45:00', '2022-02-11 05:00:00', '2022-02-11 05:15:00', '2022-02-11 05:30:00', '2022-02-11 05:45:00', '2022-02-11 06:00:00', '2022-02-11 06:15:00', '2022-02-11 06:30:00', '2022-02-11 06:45:00', '2022-02-11 07:00:00', '2022-02-11 07:15:00', '2022-02-11 07:30:00', '2022-02-11 07:45:00', '2022-02-11 08:00:00', '2022-02-11 08:15:00', '2022-02-11 08:30:00', '2022-02-11 08:45:00', '2022-02-11 09:00:00', '2022-02-11 09:15:00', '2022-02-11 09:30:00', '2022-02-11 09:45:00', '2022-02-11 10:00:00', '2022-02-11 10:15:00', '2022-02-11 10:30:00', '2022-02-11 10:45:00', '2022-02-11 11:00:00', '2022-02-11 11:15:00', '2022-02-11 11:30:00', '2022-02-11 11:45:00', '2022-02-11 12:00:00', '2022-02-11 12:15:00', '2022-02-11 12:30:00', '2022-02-11 12:45:00', '2022-02-11 13:00:00', '2022-02-11 13:15:00', '2022-02-11 13:30:00', '2022-02-11 13:45:00', '2022-02-11 14:00:00', '2022-02-11 14:15:00', '2022-02-11 14:30:00', '2022-02-11 14:45:00', '2022-02-11 15:00:00', '2022-02-11 15:15:00', '2022-02-11 15:30:00', '2022-02-11 15:45:00', '2022-02-11 16:00:00', '2022-02-11 16:15:00', '2022-02-11 16:30:00', '2022-02-11 16:45:00', '2022-02-11 17:00:00', '2022-02-11 17:15:00', '2022-02-11 17:30:00', '2022-02-11 17:45:00', '2022-02-11 18:00:00', '2022-02-11 18:15:00', '2022-02-11 18:30:00', '2022-02-11 18:45:00']
本次实验预测未来的结果： [3.2, 3.3, 3.3, 3.3, 3.2, 3.4, 3.3, 3.4, 3.3, 3.3, 3.5, 3.5, 3.2, 3.5, 3.6, 3.5, 3.4, 3.4, 3.4, 3.4, 3.2, 3.3, 3.4, 3.2, 3.4, 3.4, 3.7, 3.4, 3.0, 3.2, 3.6, 3.6, 3.7, 3.4, 3.4, 3.3, 3.3, 3.3, 3.5, 2.9, 3.4, 3.1, 3.3, 3.1, 2.7, 3.3, 3.1, 3.0, 3.0, 3.0, 3.0, 3.0, 2.9, 3.0, 3.0, 2.9, 2.9, 3.5, 3.4, 2.9, 3.2, 2.9, 2.9, 2.7, 3.5, 2.2, 3.2, 3.0, 3.0, 2.9, 3.0, 3.1, 3.1, 3.1, 3.1, 3.1]
predict chart action is completed!
loss chart action is completed!
test evaluation chart action is completed!
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2021.1.2\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.1.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/work/delivery_project/informer_ChineseNotes/main_informer_C5_多对1.py", line 531, in <module>
    df = df[df_columns]
  File "C:\ProgramData\Anaconda3\envs\torch_lts\lib\site-packages\pandas\core\frame.py", line 3810, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "C:\ProgramData\Anaconda3\envs\torch_lts\lib\site-packages\pandas\core\indexes\base.py", line 6111, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "C:\ProgramData\Anaconda3\envs\torch_lts\lib\site-packages\pandas\core\indexes\base.py", line 6174, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['true'] not in index"
python-BaseException

**Comment by helloworldzwz** [comment]
我也是遇到这个问题，请问解决了吗

**Comment by TonyEinstein** [comment]
你好，在TrueValue文件夹中加入你的预测未来的真实值文件，并且数据列要字段名为true。然后在你的文件中引用即可。

**Comment by TonyEinstein** [comment]
> 我也是遇到这个问题，请问解决了吗

你好，在TrueValue文件夹中加入你的预测未来的真实值文件，并且数据列要字段名为true。然后在initialize_parameter()函数的true_file变量中引用即可。

**Comment by helloworldzwz** [comment]
> 

感谢作者回复，我把要预测的数据从data中复制到了truevalue中并且更改了truevalue中文件的字段名为true，true_file变量中路径也更改了，用的数据就是作者1预测1模型中提供的data.csv文件，但是报错仍然没变，请问是什么原因呢
  File "c:/Users/zwz/Documents/vscode_workplace/informer_ChineseNotes-master/informer_ChineseNotes-master/main_informer_rose_1对1.py", line 528, in <module>
    df = df[df_columns]
  File "D:\ANACONDA\envs\informer\lib\site-packages\pandas\core\frame.py", line 2986, in __getitem__
    indexer = self.loc._convert_to_indexer(key, axis=1, raise_missing=True)
  File "D:\ANACONDA\envs\informer\lib\site-packages\pandas\core\indexing.py", line 1285, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "D:\ANACONDA\envs\informer\lib\site-packages\pandas\core\indexing.py", line 1092, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "D:\ANACONDA\envs\informer\lib\site-packages\pandas\core\indexing.py", line 1185, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "['true'] not in index"

**Comment by QiuliangLee** [comment]
> > 我也是遇到这个问题，请问解决了吗
> 
> 你好，在TrueValue文件夹中加入你的预测未来的真实值文件，并且数据列要字段名为true。然后在initialize_parameter()函数的true_file变量中引用即可。

作者，你好，按照你的解答进行了修改，但是还是报同样的错误。KeyError: "['true'] not in index"

**Comment by TonyEinstein** [comment]
> 

你是不是修改数据为自己的数据了。这个是一个验证实验，TrueValue文件夹是存放假设已知的未来数据，然后将预测出来的未来数据与这个比对。所以你只需要在initialize_parameter()中true_file变量声明是哪个文件，然后去创建这个excel文件并写true那一列的数据。具体的格式看TrueValue文件夹中的示例。

**Comment by TonyEinstein** [comment]
> ameter()函数的true_file变量中引用即可。

这个是一个验证实验，TrueValue文件夹是存放假设已知的未来数据，然后将预测出来的未来数据与这个比对。所以你只需要在initialize_parameter()中true_file变量声明是哪个文件，然后去创建这个excel文件并写true那一列的数据。具体的格式看TrueValue文件夹中的示例。当然也可以不使用TrueValue文件夹文件也就是不进行验证实验。

**Comment by helloworldzwz** [comment]
> 

作者你好，不进行验证实验是把initialize_parameter中的true_file注释就行了吗，我这么做的仍然是一样的错误。数据集没有改，用的是一对一rose那个数据名为data的数据。trueValue文件夹中没有data,我复制进去了并且更改了第二列格式为true

**Comment by QiuliangLee** [comment]
> > 
> 
> 你是不是修改数据为自己的数据了。这个是一个验证实验，TrueValue文件夹是存放假设已知的未来数据，然后将预测出来的未来数据与这个比对。所以你只需要在initialize_parameter()中true_file变量声明是哪个文件，然后去创建这个excel文件并写true那一列的数据。具体的格式看TrueValue文件夹中的示例。

感谢作者回复。我用的是你原代码rose中的data数据，将TrueValue下的”周-预测的rose真实价格“验证数据集第二列名字改成了true，跑的代码是main_informer_rose_1对1.py，代码没有修改。错误依旧存在。断点调试，发现569行“df = df[df_columns]”提示KeyError: "['true'] not in index"，其中df没有为true的那一列。

**Comment by TonyEinstein** [comment]
您好，经过我的查看，我的自带案例运行并无此报错，你根据我的案例改成你的数据然后再调参就可以了。
![image](https://user-images.githubusercontent.com/116338825/202844247-9067a533-e0b0-4793-bdfc-c98877a0059e.png)

**Comment by QiuliangLee** [comment]
感谢回复。想问下作者有什么调参经验可以分享下吗，试了好几次，图画出来差的很多

**Comment by TonyEinstein** [comment]
> 
主要根据数据规模调整编码器解码器层数、模型维数，最重要的是seq_len和label_len。
对了，以下是那个rose案例的结果，直接跑我的案例是可以运行的。你先根据我的案例，从main函数开始解读一下代码然后再修改对应的地方变成你的就可以了。
![image](https://user-images.githubusercontent.com/116338825/202937900-9c91e84e-2fc4-4c0b-8ebf-0f9fed8a4582.png)

**Comment by yangzhan111** [comment]
df =  df_columns[df_columns] 这一行 改成df =  df_test[df_columns]

**Comment by AUST-LJT** [comment]
![image](https://github.com/TonyEinstein/informer_ChineseNotes/assets/112917475/78ea4c0f-d2b8-43e9-8068-d97b4b16fe51)
我替换完我的数据之后出现这个错误？想问一下这是什么问题？该怎么解决？
