### ISSUE TITLE
作者您好，关于如何更换损失函数和夏普比率计算

### ISSUE THREAD

**Issue by syangyangyangs** [TonyEinstein/informer_ChineseNotes#2]
如题 作者大大您好，我想向你请教一下如何更换损失函数mse和夏普比率的计算要如何实现，同时我还想问一下对于股票价格数据，是不是我是用价量数据进行多对一的预测，要比只用收盘价的要好呢？

**Comment by syangyangyangs** [comment]
还想问一下作者，如何在输出结果时同时计算mse mae 和mape呀

**Comment by TonyEinstein** [comment]
你好，需要在exp_informer.py文件的_select_criterion函数中实现，最后在initialize_parameter()函数的loss变量中指定即可。
