### ISSUE TITLE
main_**运行后报错KeyError: "['true'] not in index"

### ISSUE THREAD

**Issue by ALi-China** [TonyEinstein/informer_ChineseNotes#4]
![image](https://user-images.githubusercontent.com/58615288/224525889-f4e95bdc-a458-46fe-b473-b3822eab0cdf.png)
报错图片在上面，希望大佬看到后可以帮忙看下，并且python=3.7下载依赖会报错

**Comment by yangzhan111** [comment]
请问你解决了吗这个问题

**Comment by ALi-China** [comment]
没有

**Comment by TonyEinstein** [comment]
你好，在 “/TrueValue/”文件夹下将真实值文件进行补充完整即可，就不会报错了。预测未来的时候无需补充真实值文件，只是在做验证实验的时候取部分数据进行做假设为未来才需要补充真实值文件。

**Comment by TonyEinstein** [comment]
详细看这里：https://github.com/TonyEinstein/informer_ChineseNotes/issues/1
