### ISSUE TITLE
line 83, in __getattr__     raise AttributeError AttributeError

### ISSUE THREAD

**Issue by Shenxiyao12** [TonyEinstein/informer_ChineseNotes#5]
![image](https://user-images.githubusercontent.com/95265223/224542547-8be354c3-eef6-4b6b-90dc-0e687eac7f8c.png)

**Comment by TonyEinstein** [comment]
您好，这种情况我建议重新下载一下项目，然后谨慎修改代码。

**Comment by LinBenZhan** [comment]
请问  这个问题解决了吗  能提供下方法吗

**Comment by Shenxiyao12** [comment]
重新下载再运行一下，不要和别的informer代码混在一起了
